### ISSUE TITLE
Translations don't work in production

### ISSUE THREAD

**Issue by rsbmk** [midudev/vota.dev#42]
# 404
The website responds with 404 when you try to see the translation.

![image](https://user-images.githubusercontent.com/64700838/150574420-8b398e85-d23f-4138-8058-0c4ee1c9a258.png)

It is most likely a problem with vercel, since it may not be capturing the url.

**Comment by edgarguitarist** [comment]
![image](https://user-images.githubusercontent.com/47311955/150579010-0de9d8ad-ed7b-42a4-b660-e9d31efa4063.png)
It's working... maybe you need to pull the code again...

Check if you already fetch upstream and pull the new code in vscode
![image](https://user-images.githubusercontent.com/47311955/150580329-59217283-6382-4c0c-b690-db6ae5b400e5.png)

**Comment by rsbmk** [comment]
@edgarguitarist I say "production" on localhost works great. But I see they already fixed it.
